[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python3",
  "gcc",
  "gnumake",
  "pkg-config",
  "cairo",
  "pango",
  "libjpeg",
  "giflib",
  "librsvg",
  "pixman",
  "fontconfig",
  "sqlite"
]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps --force",
  "npm rebuild sqlite3 --build-from-source"
]

[start]
cmd = "sh entrypoint.sh"
